task :default => :compile

PROGS = ["cpuid"]

task :compile do
  PROGS.each do |prog|
    sh [
     "as -o #{prog}.o #{prog}",
     "ld -o #{prog} #{prog}.o"
    ].join(" && ")
  end
end

task :clean do
  object_files = PROGS.map { |prog| "#{prog}.o" }
  binaries     = PROGS.map { |prog| "#{prog}" }

  sh "rm -rf #{object_files.join}"
  sh "rm -rf #{binaries.join}"
end