task :default => :compile

PROGS = ["cpuid"]
ASM_FLAGS = []

task :compile do
  PROGS.each do |prog|
    sh [
     "as #{ASM_FLAGS.join(" ")} -o #{prog}.o #{prog}",
     "ld -o #{prog} #{prog}.o"
    ].join(" && ")
  end
end

task :compile_debug do
  ASM_FLAGS << "-gstabs"
  compile
end

task :clean do
  object_files = PROGS.map { |prog| "#{prog}.o" }
  binaries     = PROGS.map { |prog| "#{prog}" }

  sh "rm -rf #{object_files.join}"
  sh "rm -rf #{binaries.join}"
end