task :default => :compile

PROGS = ["cpuid", "cpuid2"]
ASM_FLAGS = []

task :compile do
  asm_flags = ASM_FLAGS.join

  sh "as #{asm_flags} -o cpuid.o  cpuid.s  && ld -o cpuid  cpuid.o"
  sh "gcc -o cpuid2 cpuid2.s"
end

task :compile_debug do
  ASM_FLAGS << "-gstabs"
  Rake::Task[:compile].invoke
end

task :clean do
  object_files = PROGS.map { |prog| "#{prog}.o" }
  binaries     = PROGS.map { |prog| "#{prog}" }

  sh "rm -rf #{object_files.join}"
  sh "rm -rf #{binaries.join}"
end